version: "3"
services:
  back:
    build: ./back
    restart: always
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    environment:
      FLASK_APP: "app.py"
      FLASK_ENV: "development"
      FLASK_RUN_PORT: "5000"
      APP_SUPER_KEY: "youtube"
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://app_user:password@mysql:3306/app_db"
      K8S_URI: "http://192.168.0.129:8080/"
    volumes:
      - ./data/logs:/app/logs
    links:
      - mysql
    command: >
      sh -c "flask run --host 0.0.0.0"

  # front:
  #   build: ./front
  #   restart: always
  #   ports:
  #     - target: 3000
  #       published: 3000
  #       protocol: tcp
  #       mode: host
  #   environment:
  #     URL_BACK: "http://back:5000/"
  #   links:
  #     - back

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example
    links:
      - mysql
