version: "3"
services:
  back:
    build: ./back
    restart: always
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
    environment:
      FLASK_APP: "pod.py"
      FLASK_ENV: "development"
      FLASK_RUN_PORT: "5000"
      APP_SUPER_KEY: "youtube"
      DEV_DATABASE_URL: "mysql+pymysql://app_user:password@mysql:3306/app_db"
      TEST_DATABASE_URL: "mysql+pymysql://app_user:password@mysql:3306/app_db"
    links:
      - mysql
    command: >
      sh -c "flask db upgrade && flask run --host 0.0.0.0"

  front:
    build: ./front
    restart: always
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
        mode: host
    environment:
      APP_SUPER_KEY: "youtube"
    links:
      - back

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example
    links:
      - mysql
